// Generated by Selenium IDE

import org.junit.Test;

public class AddNoteTest extends TestBase{

  @Test
  public void AuthTest() {
    manager.getNavigation();
    manager.getLogin();
  }

  @Test
  public void secondTest() {
    AuthTest();
    manager.getNote();

  }
}
